name: "CD Develop Environment"
env:
  DOCKER_VERSION : ${{ github.sha }}

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - 'dev'

  workflow_dispatch:

jobs:
  build:
    if:      ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Login into our deploy registry
        uses: deploy/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push deploy images to our DEV server
        run: make docker VERSION=${{ env.DOCKER_VERSION }} ENVIRONMENT=-dev

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy DEV environment images
        uses: appleboy/ssh-action@master
        with:
          host:       ${{ secrets.SSH_HOST_DEV }}
          port:       ${{ secrets.SSH_PORT }}
          username:   ${{ secrets.SSH_USERNAME }}
          key:        ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH_DEV }}
            ./deploy.sh
